export function waitForHostReady(): Promise<void>;
export function requireHostApi(name: string): unknown;
export function requireAgentApi(): TauriTavernAgentApi;
export function requireSkillApi(): TauriTavernSkillApi;
export function requireLlmConnectionsApi(): TauriTavernLlmConnectionsApi;
export function requireSillyTavernContext(): unknown;
export function confirmAction(message: string): Promise<boolean>;
export function clone<T>(value: T): T;
export function prettyJson(value: unknown): string;
export function errorText(error: unknown): string;
