pub fn invoke_handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // Character commands
        super::character_commands::get_all_characters,
        super::character_commands::get_character,
        super::character_commands::create_character,
        super::character_commands::create_character_with_avatar,
        super::character_commands::update_character,
        super::character_commands::delete_character,
        super::character_commands::rename_character,
        super::character_commands::import_character,
        super::character_commands::export_character,
        super::character_commands::update_avatar,
        super::character_commands::get_character_chats_by_id,
        super::character_commands::clear_character_cache,
        // Chat commands
        super::chat_commands::get_all_chats,
        super::chat_commands::get_chat,
        super::chat_commands::get_character_chats,
        super::chat_commands::create_chat,
        super::chat_commands::add_message,
        super::chat_commands::rename_chat,
        super::chat_commands::delete_chat,
        super::chat_commands::search_chats,
        super::chat_commands::import_chat,
        super::chat_commands::export_chat,
        super::chat_commands::backup_chat,
        super::chat_commands::clear_chat_cache,
        super::chat_commands::save_chat,
        // User commands
        super::user_commands::get_all_users,
        super::user_commands::get_user,
        super::user_commands::get_user_by_username,
        super::user_commands::create_user,
        super::user_commands::update_user,
        super::user_commands::delete_user,
        // Settings commands
        super::settings_commands::get_settings,
        super::settings_commands::update_settings,
        super::settings_commands::save_user_settings,
        super::settings_commands::get_sillytavern_settings,
        super::settings_commands::create_settings_snapshot,
        super::settings_commands::get_settings_snapshots,
        super::settings_commands::load_settings_snapshot,
        super::settings_commands::restore_settings_snapshot,
        // World info commands
        super::world_info_commands::get_world_info,
        super::world_info_commands::save_world_info,
        super::world_info_commands::delete_world_info,
        super::world_info_commands::import_world_info,
        // User directory commands
        super::user_directory_commands::get_user_directory,
        super::user_directory_commands::get_default_user_directory,
        super::user_directory_commands::ensure_user_directories_exist,
        super::user_directory_commands::ensure_default_user_directories_exist,
        // Secret commands
        super::secret_commands::write_secret,
        super::secret_commands::read_secret_state,
        super::secret_commands::view_secrets,
        super::secret_commands::find_secret,
        super::secret_commands::delete_secret,
        super::secret_commands::rotate_secret,
        super::secret_commands::rename_secret,
        // Content commands
        super::content_commands::initialize_default_content,
        super::content_commands::is_default_content_initialized,
        // Extension commands
        super::extension_commands::get_extensions,
        super::extension_commands::install_extension,
        super::extension_commands::update_extension,
        super::extension_commands::delete_extension,
        super::extension_commands::get_extension_version,
        super::extension_commands::move_extension,
        // Avatar commands
        super::avatar_commands::get_avatars,
        super::avatar_commands::delete_avatar,
        super::avatar_commands::upload_avatar,
        // Group commands
        super::group_commands::get_all_groups,
        super::group_commands::get_group,
        super::group_commands::create_group,
        super::group_commands::update_group,
        super::group_commands::delete_group,
        super::group_commands::get_group_chat_paths,
        super::group_commands::clear_group_cache,
        // Background commands
        super::background_commands::get_all_backgrounds,
        super::background_commands::delete_background,
        super::background_commands::rename_background,
        super::background_commands::upload_background,
        // Theme commands
        super::theme_commands::save_theme,
        super::theme_commands::delete_theme,
        // Preset commands
        super::preset_commands::save_preset,
        super::preset_commands::delete_preset,
        super::preset_commands::restore_preset,
        super::preset_commands::save_openai_preset,
        super::preset_commands::delete_openai_preset,
        super::preset_commands::list_presets,
        super::preset_commands::preset_exists,
        super::preset_commands::get_preset,
        // Chat completion commands
        super::chat_completion_commands::get_chat_completions_status,
        super::chat_completion_commands::generate_chat_completion,
        // Tokenizer commands
        super::tokenizer_commands::count_openai_tokens,
        super::tokenizer_commands::encode_openai_tokens,
        super::tokenizer_commands::decode_openai_tokens,
        super::tokenizer_commands::build_openai_logit_bias,
        // Bridge commands
        super::bridge::emit_event,
        super::bridge::get_version,
        super::bridge::get_client_version,
        super::bridge::is_ready,
        super::bridge::read_frontend_template,
    ]
}
